"""add_llm_data_to_submission

Revision ID: 20f7ab94978c
Revises: b94045854af7
Create Date: 2026-04-24 07:31:18.424033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20f7ab94978c'
down_revision: Union[str, None] = 'b94045854af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_submissions', sa.Column('llm_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_submissions', 'llm_data')
    # ### end Alembic commands ###
